name: Deploy Docker Compose App to Azure Web App

on:
  push:
    branches:
      - james
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t thetygerpotatto/backend:latest ./backend

      - name: Build frontend (nginx) image
        run: docker build -t thetygerpotatto/frontend:latest ./frontend
        
      - name: Build frontend (nginx) image
        run: docker build -t thetygerpotatto/database:latest ./database




  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_81B2E37FBCD641D0B64710D86D404CE4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B4FFA0067EDE4D18BF9026D24D013299 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F49FCB12FE274161A432E1EDA33E694A }}

      - name: Deploy to Azure Web App (Docker Compose)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'stickyapp'
          slot-name: 'Production'
          multicontainer_config_file: "docker-compose.yml"


